config:
  selfUrl: https://vms-st-gateway-public-web
  authServer:
    authority: http://vms-st-authserver
    requireHttpsMetadata: "false"
    swaggerClientId: WebGateway_Swagger
    swaggerClientSecret: "1q2w3e*"
  dotnetEnv: Staging 
  redisHost: vms-st-redis
  rabbitmqHost: vms-st-rabbitmq
  elasticsearchHost: vms-st-elasticsearch

reRoutes:
  accountService:
    url: https://vms-st-authserver
  identityService:
    url: https://vms-st-identity
  administrationService:
    url: https://vms-st-administration
  catalogService:
    url: https://vms-st-catalog
  basketService:
    url: https://vms-st-basket
  orderingService:
    url: https://vms-st-ordering
  cmskitService:
    url: https://vms-st-cmskit
  paymentService:
    url: https://vms-st-payment  

ingress:
  host: vms-st-gateway-web-public
  tlsSecret: vms-wildcard-tls

image:
  repository: Arslan.Vms/gateway-web-public
  tag: latest
  pullPolicy: IfNotPresent

env: {}