version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 30s
        retries: 3
    restart: unless-stopped
    networks: 
      - arslan.vms-network

  redis:
    container_name: redis
    image: redis:alpine   
    volumes:
       - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    restart: unless-stopped
    networks: 
      - arslan.vms-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    depends_on:
      - postgres-db 
    restart: unless-stopped
    networks:
      - arslan.vms-network

  postgres-db:
    container_name: postgres-db
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5  
    networks: 
      - arslan.vms-network

  mssql-db:
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
       - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-P1q2w3E**", "-Q", "select 1"]
      interval: 10s
      timeout: 5s
      retries: 5 
    restart: unless-stopped 
    networks: 
      - arslan.vms-network 

volumes:
  postgres_data:
  mssql_data:
  mongodb_data:
  redis_data:

networks:
  arslan.vms-network:
    external: true