version: '3.7'

name: arslan-vms
services:
  vms-lb:
    image: nginx:1.21
    container_name: vms-load-balancer-container
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - vms-administration 
      - vms-identity
      - vms-inventory
      - vms-order
      - vms-payment
      - vms-planner
      - vms-product
      - vms-vehicle
      - vms-gateway-web
      - vms-web
    restart: on-failure
    networks:
      - arslan.vms-network

  vms-administration:
    image: arslan.vms/service-administration:latest
    container_name: vms-service-administration-container
    build:
      context: ../../
      dockerfile: services/administration/src/Arslan.Vms.AdministrationService.HttpApi.Host/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - App__SelfUrl=https://vms-st-administration
      - App__CorsOrigins=https://gateway-web,gateway-web-public
      - RemoteServices__AbpIdentity__BaseUrl=vms-st-identity
      - RemoteServices__AbpIdentity__UseCurrentAccessToken=false
      - ConnectionStrings__AdministrationService=Server=mssql-db;Database=VmsAdministration;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - AuthServer__Authority=http://vms-st-authserver
      - AuthServer__RequireHttpsMetadata=false
      - IdentityClients__Default__Authority=http://vms-st-identity
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - RabbitMQ__EventBus__ClientName=Evc_AdministrationService
      - RabbitMQ__EventBus__ExchangeName=Arslan.Vms
      - Redis__IsEnabled=true
      - Redis__Configuration=redis
    depends_on:
      redis:
        condition: service_healthy
      mssql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks: 
      - arslan.vms-network
  
  vms-identity:
    image: arslan.vms/service-identity:latest
    container_name: vms-service-identity-container
    build:
      context: ../../
      dockerfile: services/identity/src/Arslan.Vms.IdentityService.HttpApi.Host/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - App__SelfUrl=https://vms-st-identity
      - App__CorsOrigins=https://gateway-web,gateway-web-public
      - AuthServer__Authority=http://vms-st-authserver
      - AuthServer__RequireHttpsMetadata=false
      - ConnectionStrings__AdministrationService=Server=mssql-db;Database=VmsAdministration;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - ConnectionStrings__IdentityService=Server=mssql-db;Database=VmsIdentity;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - RabbitMQ__EventBus__ClientName=Evc_IdentityService
      - RabbitMQ__EventBus__ExchangeName=Arslan.Vms
      - Redis__IsEnabled=true
      - Redis__Configuration=redis
      - IdentityServerClients__Web__RootUrl=https://vms-st-web
      - IdentityServerClients__PublicWeb__RootUrl=https://vms-st-public-web
      - IdentityServerClients__WebGateway__RootUrl=https://vms-st-gateway-web
      - IdentityServerClients__PublicWebGateway__RootUrl=https://vms-st-gateway-web-public
      - IdentityServerClients__IdentityService__RootUrl=https://vms-st-identity
      - IdentityServerClients__AdministrationService__RootUrl=https://vms-st-administration
      - IdentityServerClients__AccountService__RootUrl=https://vms-st-authserver
      - IdentityServerClients__CatalogService__RootUrl=https://vms-st-catalog
      - IdentityServerClients__BasketService__RootUrl=https://vms-st-basket     
      - IdentityServerClients__OrderingService__RootUrl=https://vms-st-ordering
      - IdentityServerClients__CmskitService__RootUrl=https://vms-st-cmskit
      - IdentityServerClients__PaymentService__RootUrl=https://vms-st-payment
    depends_on:
      redis:
        condition: service_healthy
      mssql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks: 
      - arslan.vms-network
  
  vms-inventory:
    image: arslan.vms/service-inventory:latest
    container_name: vms-service-inventory-container
    build:
      context: ../../
      dockerfile: services/inventory/src/Arslan.Vms.InventoryService.HttpApi.Host/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;http://+:81;
      - App__SelfUrl=https://vms-st-catalog
      - App__CorsOrigins=https://vms-st-gateway-web,https://vms-st-gateway-web-public,https://vms-st-public-web,https://vms-st-web
      - AuthServer__Authority=http://vms-st-authserver
      - AuthServer__RequireHttpsMetadata=false
      - Kestrel__EndPoints__Http__Url=http://docker.host.internal:80
      - Kestrel__EndPoints__gRPC__Url=http://docker.host.internal:81
      - Kestrel__EndPoints__gRPC__Protocols=Http2
      - ConnectionStrings__AdministrationService=Server=mssql-db;Database=VmsAdministration;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - ConnectionStrings__InventoryService=Server=mssql-db;Database=VmsInventory;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - RabbitMQ__EventBus__ClientName=Evc_InventoryService
      - RabbitMQ__EventBus__ExchangeName=Arslan.Vms
      - Redis__IsEnabled=true
      - Redis__Configuration=redis
    depends_on:
      redis:
        condition: service_healthy
      mssql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure  
    networks: 
      - arslan.vms-network
  
  vms-order:
    image: arslan.vms/service-order:latest
    container_name: vms-service-order-container
    build:
      context: ../../
      dockerfile: services/order/src/Arslan.Vms.OrderService.HttpApi.Host/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - App__SelfUrl=https://vms-st-basket
      - App__CorsOrigins=https://vms-st-gateway-web,https://vms-st-gateway-web-public,https://vms-st-public-web
      - RemoteServices__Catalog__BaseUrl=http://vms-st-catalog:80
      - RemoteServices__Catalog__GrpcUrl=http://vms-st-catalog:81
      - ConnectionStrings__AdministrationService=Server=mssql-db;Database=VmsAdministration;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - ConnectionStrings__OrderService=Server=mssql-db;Database=VmsOrder;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - RabbitMQ__EventBus__ClientName=Evc_OrderService
      - RabbitMQ__EventBus__ExchangeName=Arslan.Vms
      - Redis__IsEnabled=true
      - Redis__Configuration=redis
    depends_on:
      redis:
        condition: service_healthy
      mssql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure  
    networks: 
      - arslan.vms-network
  
  vms-payment:
    image: arslan.vms/service-payment:latest
    container_name: vms-service-payment-container
    build:
      context: ../../
      dockerfile: services/payment/src/Arslan.Vms.PaymentService.HttpApi.Host/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;
      - App__SelfUrl=https://vms-st-ordering
      - App__CorsOrigins=https://vms-st-gateway-web,https://vms-st-gateway-web-public,https://vms-st-web
      - ConnectionStrings__AdministrationService=Server=mssql-db;Database=VmsAdministration;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - ConnectionStrings__PaymentService=Server=mssql-db;Database=VmsPayment;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - RabbitMQ__EventBus__ClientName=Evc_PaymentService
      - RabbitMQ__EventBus__ExchangeName=Arslan.Vms
      - Redis__IsEnabled=true
      - Redis__Configuration=redis
    depends_on:
      redis:
        condition: service_healthy
      mssql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure  
    networks: 
      - arslan.vms-network
  
  vms-planner:
    image: arslan.vms/service-planner:latest
    container_name: vms-service-planner-container
    build:
      context: ../../
      dockerfile: services/planner/src/Arslan.Vms.PlannerService.HttpApi.Host/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;
      - App__SelfUrl=https://vms-st-cmskit
      - App__CorsOrigins=https://vms-st-gateway-web,https://vms-st-gateway-web-public
      - ConnectionStrings__AdministrationService=Server=mssql-db;Database=VmsAdministration;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - ConnectionStrings__PlannerService=Server=mssql-db;Database=VmsPlanner;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - RabbitMQ__EventBus__ClientName=Evc_PlannerService
      - RabbitMQ__EventBus__ExchangeName=Arslan.Vms
      - Redis__IsEnabled=true
      - Redis__Configuration=redis
    depends_on:
      redis:
        condition: service_healthy
      mssql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure  
    networks: 
      - arslan.vms-network
  
  vms-product:
    image: arslan.vms/service-product:latest
    container_name: vms-service-product-container
    build:
      context: ../../
      dockerfile: services/product/src/Arslan.Vms.ProductService.HttpApi.Host/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;
      - App__SelfUrl=https://vms-st-payment
      - App__CorsOrigins=https://vms-st-gateway-web,https://vms-st-gateway-web-public      
      - ConnectionStrings__AdministrationService=Server=mssql-db;Database=VmsAdministration;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - ConnectionStrings__ProductService=Server=mssql-db;Database=VmsProduct;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - RabbitMQ__EventBus__ClientName=Evc_ProductService
      - RabbitMQ__EventBus__ExchangeName=Arslan.Vms
      - Redis__IsEnabled=true
      - Redis__Configuration=redis
    depends_on:
      redis:
        condition: service_healthy
      mssql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure  
    networks: 
      - arslan.vms-network

  vms-vehicle:
    image: arslan.vms/service-vehicle:latest
    container_name: vms-service-vehicle-container
    build:
      context: ../../
      dockerfile: services/vehicle/src/Arslan.Vms.VehicleService.HttpApi.Host/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;
      - App__SelfUrl=https://vms-st-payment
      - App__CorsOrigins=https://vms-st-gateway-web,https://vms-st-gateway-web-public      
      - ConnectionStrings__AdministrationService=Server=mssql-db;Database=VmsAdministration;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - ConnectionStrings__VehicleService=Server=mssql-db;Database=VmsVehicle;UID=sa;PASSWORD=1q2w3E**;Integrated Security=True;Trusted_Connection=False;TrustServerCertificate=True;Pooling=True;Max Pool Size=1000;Timeout=300
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - RabbitMQ__EventBus__ClientName=Evc_VehicleService
      - RabbitMQ__EventBus__ExchangeName=Arslan.Vms
      - Redis__IsEnabled=true
      - Redis__Configuration=redis
    depends_on:
      redis:
        condition: service_healthy
      mssql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure  
    networks: 
      - arslan.vms-network
 
  vms-gateway-web:
    image: arslan.vms/gateway-web:latest
    container_name: vms-gateway-web-container
    build:
      context: ../../
      dockerfile: gateways/web/src/Arslan.Vms.WebGateway/Dockerfile
    environment:
      #- ASPNETCORE_ENVIRONMENT=Docker # Yarp can't resolve dns, needs to be overridden
      - ASPNETCORE_URLS=http://+:80;
      - App__SelfUrl=https://vms-st-gateway-web
      - App__CorsOrigins=https://vms-st-web
      - AuthServer__Authority=http://vms-st-authserver
      - AuthServer__RequireHttpsMetadata=false
      - Redis__Configuration=redis
      - ReverseProxy__Clusters__accountCluster__Destinations__destination1__Address=http://vms-st-authserver
      - ReverseProxy__Clusters__identityCluster__Destinations__destination1__Address=http://vms-st-identity
      - ReverseProxy__Clusters__administrationCluster__Destinations__destination1__Address=http://vms-st-administration
      - ReverseProxy__Clusters__catalogCluster__Destinations__destination1__Address=http://vms-st-catalog
      - ReverseProxy__Clusters__orderingCluster__Destinations__destination1__Address=http://vms-st-ordering
      - ReverseProxy__Clusters__cmskitCluster__Destinations__destination1__Address=http://vms-st-cmskit
      - ReverseProxy__Clusters__feature-management-cluster__Destinations__destination1__Address=http://vms-st-administration
      - ReverseProxy__Clusters__permission-management-cluster__Destinations__destination1__Address=http://vms-st-administration
      - ReverseProxy__Clusters__setting-management-cluster__Destinations__destination1__Address=http://vms-st-administration
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure  
    networks: 
      - arslan.vms-network

  vms-web:
    image: arslan.vms/app-web:latest
    container_name: vms-app-web-container
    build:
      context: ../../
      dockerfile: apps/angular1/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks: 
      - arslan.vms-network

networks:
  arslan.vms-network:
    external: true
