config:
  selfUrl: # https://vms-st-catalog
  corsOrigins: # https://vms-st-gateway-web,https://vms-st-gateway-public-web,https://vms-st-public,https://vms-st-web
  connectionStrings:
    catalogService: #
    administrationService: #
  authServer:
    authority: http://vms-st-authserver
    requireHttpsMetadata: "false"
    swaggerClientId: WebGateway_Swagger
    swaggerClientSecret: "1q2w3e*"
  dotnetEnv: Staging
  redisHost: vms-st-redis
  rabbitmqHost: vms-st-rabbitmq
  elasticsearchHost: vms-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  grpcPort: 81
  kestrel:
    httpUrl: http://vms-st-catalog:80
    httpProtocols: Http1AndHttp2
    grpcUrl: http://vms-st-catalog:81
    grpcProtocols: Http2

ingress:
  host: vms-st-catalog
  tlsSecret: vms-wildcard-tls

image:
  repository: Arslan.Vms/service-catalog
  tag: latest
  pullPolicy: IfNotPresent

env: {
  # ASPNETCORE_URLS=http://+:80;http://+:81
}
    