config:
  selfUrl: https://demomicro-st-authserver.Arslan.Vms.com   
  corsOrigins: https://demomicro-st-gateway.Arslan.Vms.com,https://demomicro-st-gateway-public.Arslan.Vms.com,https://demomicro-st-identity.Arslan.Vms.com,https://demomicro-st-administration.Arslan.Vms.com,https://demomicro-st-basket.Arslan.Vms.com,https://demomicro-st-catalog.Arslan.Vms.com,https://demomicro-st-order.Arslan.Vms.com,https://demomicro-st-cmskit.Arslan.Vms.com,https://demomicro-st-payment.Arslan.Vms.com,https://demomicro-st-admin.Arslan.Vms.com,https://demomicro-st-Arslan.Vms.com
  allowedRedirectUrls: https://demomicro-st-admin.Arslan.Vms.com
  authServer:
    authority: https://demomicro-st-authserver.Arslan.Vms.com
    requireHttpsMetadata: "false"
  connectionStrings:
    administrationService: "Host=postgresdb-postgresdb;Port=5432;Database=Arslan.Vms_Administration;User ID=postgres;password=myPassw0rd;Pooling=false"
    identityService: "Host=postgresdb-postgresdb;Port=5432;Database=Arslan.Vms_Identity;User ID=postgres;password=myPassw0rd;Pooling=false"
  dotnetEnv: Production
  redisHost: redis-redis
  rabbitmqHost: rabbitmq-rabbitmq
  elasticsearchHost: elasticsearch-elasticsearch
ingress:
  host: demomicro-st-authserver.Arslan.Vms.com
  tlsSecret: vms-wildcard-tls
image:
  repository: "volocr.azurecr.io/demomicro/app-authserver"
  tag: 1.0.1