config:
  selfUrl: # https://vms-st-identity
  corsOrigins: # https://vms-st-gateway-web,https://vms-st-gateway-public-web,https://vms-st-gateway-internal
  connectionStrings:
    identityService: #
    administrationService: #
  authServer:
    authority: http://vms-st-authserver
    requireHttpsMetadata: "false"
    swaggerClientId: WebGateway_Swagger
    swaggerClientSecret: "1q2w3e*"
  dotnetEnv: Staging
  redisHost: vms-st-redis
  rabbitmqHost: vms-st-rabbitmq
  elasticsearchHost: vms-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

# Seeded clients 
identityServerClients:
  webRootUrl: #  
  publicWebRootUrl: #
  webGatewayRootUrl: #
  publicWebGatewayRootUrl: #
  accountServiceRootUrl: #  
  identityServiceRootUrl: #
  administrationServiceRootUrl: #
  basketServiceRootUrl: #
  catalogServiceRootUrl: #
  orderingServiceRootUrl: #
  paymentServiceRootUrl: #
  cmskitServiceRootUrl: #
  

ingress:
  host: vms-st-identity
  tlsSecret: vms-wildcard-tls

image:
  repository: Arslan.Vms/service-identity
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    