config:
  selfUrl: # https://vms-st-basket
  corsOrigins: # https://vms-st-gateway-web,https://vms-st-gateway-public-web,https://vms-st-public
  connectionStrings:
    administrationService: #
  authServer:
    authority: http://vms-st-authserver
    requireHttpsMetadata: "false"
    swaggerClientId: "WebGateway_Swagger"
    swaggerClientSecret: "1q2w3e*"
  dotnetEnv: Staging
  redisHost: vms-st-redis
  rabbitmqHost: vms-st-rabbitmq
  elasticsearchHost: vms-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  remoteServices:
    catalogBaseUrl: #
    catalogGrpcUrl: #

ingress:
  host: vms-st-basket
  tlsSecret: vms-wildcard-tls

image:
  repository: Arslan.Vms/service-basket
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    