config:
  selfUrl: # https://vms-st-gateway-web
  corsOrigins: # localhost:4200
  globalConfigurationBaseUrl: # http://vms-st-gateway-web
  authServer:
    authority: http://vms-st-authserver
    requireHttpsMetadata: "false"
    swaggerClientId: WebGateway_Swagger
    swaggerClientSecret: "1q2w3e*"
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchHost: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
reRoutes:
  accountService:
    url: http://vms-st-authserver
  identityService:
    url: http://vms-st-identity
  administrationService:
    url: http://vms-st-administration
  catalogService:
    url: http://vms-st-catalog
  orderingService:
    url: http://vms-st-order
ingress:
  host: # vms-st-gateway-web
  tlsSecret: vms-wildcard-tls

image:
  repository: Arslan.Vms/gateway-web
  tag: latest
  pullPolicy: IfNotPresent

env: {}